//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarProjectDemo.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        public int AdminId { get; set; }
        public string AdminName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string Authority { get; set; }
    }
}
