//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarProjectDemo.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int CarId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> ColorId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> BodyTypeId { get; set; }
        public Nullable<int> GearId { get; set; }
        public Nullable<int> FuelTypeId { get; set; }
        public string ModelYear { get; set; }
        public string Decription { get; set; }
        public Nullable<int> ActionType { get; set; }
    
        public virtual BodyTypes BodyTypes { get; set; }
        public virtual Brands Brands { get; set; }
        public virtual Colors Colors { get; set; }
        public virtual FuelTypes FuelTypes { get; set; }
        public virtual Gears Gears { get; set; }
        public virtual Models Models { get; set; }
    }
}
